import './globals.css';
import {songMyung, firaMono, marckScript, rubikMonoOne} from '../fonts';
import classNames from 'classnames';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          songMyung.variable,
          firaMono.variable,
          marckScript.variable,
          rubikMonoOne.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
